package:
  name: xenon-cli
  version: 2.2.0
source:
  sha256: bca506b94ca212904233289ef8066b31fe87a9e01db772c31e23bf0f788e33a7
  url: https://github.com/NLeSC/xenon-cli/releases/download/v2.2.0/xenon-cli-shadow-2.2.0.tar
requirements:
  run:
    - openjdk 8.*
about:
  home: https://github.com/NLeSC/Xenon
  license: Apache 2.0
  summary: If you are using remote machines to do your computations, and don’t feel like learning and implementing many different APIs and do no not want to program, Xenon Command Line Interface (CLI) is the tool for you.
