package:
  name: xenon-cli
  version: 2.2.1
source:
  path: ../../build/install/xenon-cli-shadow
requirements:
  run:
    - openjdk 8.*
about:
  home: https://github.com/NLeSC/Xenon
  license: Apache 2.0
  summary: If you are using remote machines to do your computations, and don’t feel like learning and implementing many different APIs and do no not want to program, Xenon Command Line Interface (CLI) is the tool for you.
